services:
  web:
    image: my-lamp-web
    build: . #Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/src # htmlディレクトリをコンテナへマウント
      - ./public:/var/www/html/public
    working_dir: /var/www/html/public # 作業ディレクトリ
    command : "apache2-foreground" # apache2を実行

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: mydb
      MYSQL_USER: a
      MYSQL_PASSWORD: a
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
